version: "3"

services:
  service_a:
    container_name: service_a
    build:
      context: a/
    networks:
      - demo
    ports:
      - 80

  service_b:
    container_name: service_b
    build:
      context: b/
    networks:
      - demo
    ports:
      - 80

  haproxy:
    container_name: haproxy
    build:
      context: haproxy/
    networks:
      - demo
    ports:
      - 80:80

networks:
  demo: